ScreenManager:
    Screen:
        name: 'Main'

        BoxLayout:
            padding: [12,15,12,6]
            orientation: 'vertical'

            ScrollView:
                size_hint: (1,1)
                
                GridLayout:
                    id: fund_list
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 10
                    
    Screen:
        name: 'fund_detail'

        BoxLayout:
            orientation: 'vertical'
            padding: [12,15,12,6]

            BoxLayout:
                size_hint_y: None
                height: 50

                Button:
                    text: 'Back'
                    font_size: '18sp'
                    on_release: app.root.current = "Main"
                    size_hint_x: 0.2

                Widget:

            ScrollView:
                size_hint: (1,1)

                GridLayout:
                    id: instalment_list
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 25

                    
                
        


